import Head from 'next/head';
import Image from 'next/image';
import classes from '../styles/Home.module.css';

function HomePage() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div  className={classes.header}>
      <h1>Home page</h1>
      </div>
      
    </div>
  );

}


export default HomePage;