import  Head from 'next/head';
import Header from '../components/Header';
import Temp from '../components/Temp';

function HomePage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <Header />
    <Temp />

    </div>
  );

}


export default HomePage;